### ISSUE TITLE
opsicle instances is broken on v2

### ISSUE THREAD

**Issue by anfleene** [sportngin/opsicle#107]
```
$ opsicle --debug instances staging                                                                                                                    
error: undefined method `to_h' for [[35, [1]], [0, [0]]]:Array
/usr/local/Cellar/gem-opsicle/2.1.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:248:in `block (2 levels) in recalc_column_widths': undefined method `to_h' for [[35, [1]], [0, [0]]]:Array (NoMethodError)
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:225:in `each'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:225:in `block in recalc_column_widths'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:223:in `each'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:223:in `recalc_column_widths'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:339:in `column_widths'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:97:in `column_width'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/terminal-table-1.7.2/lib/terminal-table/separator.rb:7:in `block in render'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/terminal-table-1.7.2/lib/terminal-table/separator.rb:6:in `map'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/terminal-table-1.7.2/lib/terminal-table/separator.rb:6:in `render'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:142:in `block in render'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:142:in `map'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/terminal-table-1.7.2/lib/terminal-table/table.rb:142:in `render'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/opsicle-2.1.0/lib/opsicle/commands/list_instances.rb:21:in `puts'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/opsicle-2.1.0/lib/opsicle/commands/list_instances.rb:21:in `puts'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/opsicle-2.1.0/lib/opsicle/commands/list_instances.rb:21:in `print'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/opsicle-2.1.0/lib/opsicle/commands/list_instances.rb:13:in `execute'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/opsicle-2.1.0/bin/opsicle:210:in `block (2 levels) in <top (required)>'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/gli-2.14.0/lib/gli/command_support.rb:126:in `call'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/gli-2.14.0/lib/gli/command_support.rb:126:in `execute'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/gli-2.14.0/lib/gli/app_support.rb:296:in `block in call_command'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/gli-2.14.0/lib/gli/app_support.rb:309:in `call'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/gli-2.14.0/lib/gli/app_support.rb:309:in `call_command'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/gli-2.14.0/lib/gli/app_support.rb:83:in `run'
	from /usr/local/Cellar/gem-opsicle/2.1.0/gems/opsicle-2.1.0/bin/opsicle:249:in `<top (required)>'
	from /usr/local/bin/opsicle:5:in `load'
	from /usr/local/bin/opsicle:5:in `<main>'
```

**Comment by nicksieger** [comment]
For reference:

```
$ ls -l /usr/local/opt/gem-opsicle/specifications/
total 96
-rw-r--r--  1 X  X  1174 Sep 21 10:17 aws-sdk-2.6.2.gemspec
-rw-r--r--  1 X  X  1204 Sep 21 10:17 aws-sdk-core-2.6.2.gemspec
-rw-r--r--  1 X  X  1231 Sep 21 10:17 aws-sdk-resources-2.6.2.gemspec
-rw-r--r--  1 X  X  3516 Sep 21 10:17 curses-1.0.2.gemspec
-rw-r--r--  1 X  X  2874 Sep 21 10:17 gli-2.14.0.gemspec
-rw-r--r--  1 X  X  1572 Sep 21 10:17 hashdiff-0.3.0.gemspec
-rw-r--r--  1 X  X  1784 Sep 21 10:17 highline-1.7.8.gemspec
-rw-r--r--  1 X  X   714 Sep 21 10:17 jmespath-1.3.1.gemspec
-rw-r--r--  1 X  X  1604 Sep 21 10:17 minitar-0.5.4.gemspec
-rw-r--r--  1 X  X  3123 Sep 21 10:17 opsicle-2.0.2.gemspec
-rw-r--r--  1 X  X  1982 Sep 21 10:17 terminal-table-1.7.2.gemspec
-rw-r--r--  1 X  X  1643 Sep 21 10:17 unicode-display_width-1.1.1.gemspec
```

**Comment by anfleene** [comment]
It seems like it might be related to https://github.com/sportngin/opsicle/pull/91/files#diff-19baf641d32796c525b55c0e9e957f2bR23

**Comment by vivekbisen** [comment]
[Terminal-table](https://github.com/tj/terminal-table/pull/76/files#diff-cc6d95e7d0426a8ffc4fb8ecbc218270R248) breaks with [old ruby](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/ruby.sh#L32) used by brew in MacOS. [This PR](https://github.com/tj/terminal-table/pull/80) fixes the issue.

**Comment by vivekbisen** [comment]
We could either wait for a newer version of `terminal-table` 💎 or specify in opsicle gemspec dependency to use anything lower than 1.7.2. @anfleene thoughts?

**Comment by anfleene** [comment]
did your PR not fix it? I'm for limiting in the gemspec if it didn't.

**Comment by vivekbisen** [comment]
It did, but that's a gem. Until a new version of it is out in rubygems, it's not gonna make any difference.

**Comment by anfleene** [comment]
Let's limit the version in the gemspec for the time being.

**Comment by vivekbisen** [comment]
So, now that [terminal-table 1.7.3](https://github.com/tj/terminal-table/releases/tag/v1.7.3) is out, if we reinstall opsicle via brew-gem, the issue will dissappear. Just run 
```sh
brew gem uninstall opsicle && brew gem install opsicle
